server:
  port: 7090
  servlet:
    context-path: /api
    session:
      timeout: PT60M

spring:
  mvc:
    favicon:
      enable: false
  datasource:
    url: jdbc:mysql://localhost:3306/table?serverTimezone=GMT
    username: root
    password: jjx0924.
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  mail:
    host: smtp.qq.com
    port: 465
    username: 1665353392@qq.com
    password: jtrpnkvrcpbsdaee
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

  data:
    redis:
      database: 0
      host: 39.101.70.154
      port: 6379
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
      timeout: 2000
      password: 123456
logging:
  level:
    root: debug

project:
  folder: D:\Java\Project\springbootProject\YixiaPan\resource

admin:
  emails: 1665353392@qq.com

qq:
  app:
    id: 12333
    key: 2222222
  url:
    authorization: https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s
    access:
      token: https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s
    openid: https://graph.qq.com/oauth2.0/me?access_token=%S
    user:
      info: https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s
    redirect: http://easypan.wuhancoder.com/qqlogincalback

mybatis:
  configuration:
    map-underscore-to-camel-case: true
